### ISSUE TITLE
Exception when connecting with mininet network

### ISSUE THREAD

**Issue by keichi** [trema/trema#388]
I'm trying to use trema as a remote controller for mininet. When I launch trema after creating a virtual network with mininet, trema terminates with the following error:

```
keichi@keichi-exp1:~/hello_trema$ ./bin/trema run lib/hello_trema.rb -c trema.conf
Trema started.
Hello 0xabc!
error: end of file reached
/home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/switch.rb:77:in `readpartial': end of file reached (EOFError)
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/switch.rb:77:in `block in drain'
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/switch.rb:76:in `loop'
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/switch.rb:76:in `drain'
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/switch.rb:67:in `read_openflow_binary'
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/switch.rb:41:in `read'
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/switch.rb:50:in `exchange_hello_messages'
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/switch.rb:24:in `init'
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/controller.rb:233:in `create_and_register_new_switch'
    from /home/keichi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/trema-ccc3dc6de142/lib/trema/controller.rb:218:in `block in start_switch_thread'
```

The controller I'm using here is trema/hello_trema@50a6dbf4eb9c68ad538783c6a047f2f83493343d. 

I'm launching mininet with the following options (mininet 2.1.0 + Open vSwitch 2.0.2):

``` bash
$ sudo mn --controller=remote,ip=127.0.0.1,port=6633
```

**Comment by hkwi** [comment]
Could not reproduce this under the following condition:

```
rbenv global 2.1.3
gem install bundler
bundler update
```

**Comment by nmdoliveira** [comment]
I get the same error.
Tested with Ruby 2.1.0, 2.1.3 and 2.2.2, none worked.
Only thing that worked was switching back to Trema 0.4.7.

**Comment by yasuhito** [comment]
Thank you for the information. I guess Trema is failing when trying to parse an OpenFlow header coming from mininet network. Could you send me the packet dump (header_dump.raw) by adding the following line to the switch.rb file?

```ruby
def read_openflow_binary
  header_binary = drain(OPENFLOW_HEADER_LENGTH)
  File.open('/tmp/header_dump.raw', 'w') { |f| f.write header_binary } # add this line
  # ...
```
